# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#                 TaskQueue:    0 /    6 =   0.00%
#                      Task:    0 /    2 =   0.00%

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'utility' 

class TestTask < Test::Unit::TestCase
  def test_call
    raise NotImplementedError, 'Need to write test_call'
  end

  def test_invoke
    raise NotImplementedError, 'Need to write test_invoke'
  end

  def test_params
    raise NotImplementedError, 'Need to write test_params'
  end
end

class TestTaskQueue < Test::Unit::TestCase
  def test_clear_and_halt
    raise NotImplementedError, 'Need to write test_clear_and_halt'
  end

  def test_pause
    raise NotImplementedError, 'Need to write test_pause'
  end

  def test_start
    raise NotImplementedError, 'Need to write test_start'
  end
end

# Number of errors detected: 8
