# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#              TagLibTagger:    0 /    3 =   0.00%

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'library' 

require 'taggers/estelle-taglib'

class TestTagLibTagger < Test::Unit::TestCase
  def test_class_instance
    raise NotImplementedError, 'Need to write test_class_instance'
  end

  def test_get_tags_eh
    raise NotImplementedError, 'Need to write test_get_tags_eh'
  end

  def test_song_info
    raise NotImplementedError, 'Need to write test_song_info'
  end
end

# Number of errors detected: 4
