# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#           EstelleSettings:    0 /    3 =   0.00%

$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'settings' 

class TestEstelleSettings < Test::Unit::TestCase
  def test_class_load
    raise NotImplementedError, 'Need to write test_class_load'
  end

  def test_save
    raise NotImplementedError, 'Need to write test_save'
  end

  def test_soundtrack_table
    raise NotImplementedError, 'Need to write test_soundtrack_table'
  end

  def test_tagsubst_table
    raise NotImplementedError, 'Need to write test_tagsubst_table'
  end
end

# Number of errors detected: 5
