#!/bin/sh

export OLDPWD=$PWD
cd ../lib
if [ -e test_$1 ]; then
	zentest $1 ../tests/test_$1 > missing
	cat missing >> ../tests/test_$1
	rm -f missing
else
	zentest $1 > ../tests/test_$1 
fi
cd $OLDPWD
