# Code Generated by ZenTest v. 3.4.3
#                 classname: asrt / meth =  ratio%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestConfig < Test::Unit::TestCase
  def test_class_datadir
    raise NotImplementedError, 'Need to write test_class_datadir'
  end

  def test_class_expand
    raise NotImplementedError, 'Need to write test_class_expand'
  end

  def test_class_gem_original_datadir
    raise NotImplementedError, 'Need to write test_class_gem_original_datadir'
  end
end

# Number of errors detected: 4
