# Code Generated by ZenTest v. 3.4.3
#                 classname: asrt / meth =  ratio%
#                  Platform:    0 /    2 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestPlatform < Test::Unit::TestCase
  def test_class_os
    raise NotImplementedError, 'Need to write test_class_os'
  end

  def test_class_settings_file_path
    raise NotImplementedError, 'Need to write test_class_settings_file_path'
  end
end

# Number of errors detected: 3
