# Code Generated by ZenTest v. 3.4.3
#                 classname: asrt / meth =  ratio%
#                      Song:    0 /    9 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestSong < Test::Unit::TestCase
  def test_class_sub_table
    raise NotImplementedError, 'Need to write test_class_sub_table'
  end

  def test_class_sub_table_equals
    raise NotImplementedError, 'Need to write test_class_sub_table_equals'
  end

  def test_checked_tag
    raise NotImplementedError, 'Need to write test_checked_tag'
  end

  def test_get_canonical_artist
    raise NotImplementedError, 'Need to write test_get_canonical_artist'
  end

  def test_index
    raise NotImplementedError, 'Need to write test_index'
  end

  def test_index_equals
    raise NotImplementedError, 'Need to write test_index_equals'
  end

  def test_to_hash
    raise NotImplementedError, 'Need to write test_to_hash'
  end
end

# Number of errors detected: 8
