# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#                  Platform:    0 /    5 =   0.00%

$:.unshift File.join(File.dirname(__FILE__), '..', '..', 'lib')

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'platform'

class TestPlatform < Test::Unit::TestCase
	def test_class_binary_dir
		raise NotImplementedError, 'Need to write test_class_binary_dir'
	end

	def test_class_home_dir
		assert (Platform.home_dir == "/Users/paul/.estelle")
	end

	def test_class_os
		raise NotImplementedError, 'Need to write test_class_os'
	end

	def test_class_settings_file_path
		raise NotImplementedError, 'Need to write test_class_settings_file_path'
	end

	def test_class_which
		raise NotImplementedError, 'Need to write test_class_which'
	end
end

# Number of errors detected: 6
