# Code Generated by ZenTest v. 3.6.1
#                 classname: asrt / meth =  ratio%
#                      File:    0 /   24 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestFile < Test::Unit::TestCase
  def test_class_atime
    raise NotImplementedError, 'Need to write test_class_atime'
  end

  def test_class_basename
    raise NotImplementedError, 'Need to write test_class_basename'
  end

  def test_class_blockdev_eh
    raise NotImplementedError, 'Need to write test_class_blockdev_eh'
  end

  def test_class_chardev_eh
    raise NotImplementedError, 'Need to write test_class_chardev_eh'
  end

  def test_class_chmod
    raise NotImplementedError, 'Need to write test_class_chmod'
  end

  def test_class_chown
    raise NotImplementedError, 'Need to write test_class_chown'
  end

  def test_class_ctime
    raise NotImplementedError, 'Need to write test_class_ctime'
  end

  def test_class_delete
    raise NotImplementedError, 'Need to write test_class_delete'
  end

  def test_class_directory_eh
    raise NotImplementedError, 'Need to write test_class_directory_eh'
  end

  def test_class_dirname
    raise NotImplementedError, 'Need to write test_class_dirname'
  end

  def test_class_executable_eh
    raise NotImplementedError, 'Need to write test_class_executable_eh'
  end

  def test_class_executable_real_eh
    raise NotImplementedError, 'Need to write test_class_executable_real_eh'
  end

  def test_class_exist_eh
    raise NotImplementedError, 'Need to write test_class_exist_eh'
  end

  def test_class_exists_eh
    raise NotImplementedError, 'Need to write test_class_exists_eh'
  end

  def test_class_expand_path
    raise NotImplementedError, 'Need to write test_class_expand_path'
  end

  def test_class_extname
    raise NotImplementedError, 'Need to write test_class_extname'
  end

  def test_class_file_eh
    raise NotImplementedError, 'Need to write test_class_file_eh'
  end

  def test_class_fnmatch
    raise NotImplementedError, 'Need to write test_class_fnmatch'
  end

  def test_class_fnmatch_eh
    raise NotImplementedError, 'Need to write test_class_fnmatch_eh'
  end

  def test_class_ftype
    raise NotImplementedError, 'Need to write test_class_ftype'
  end

  def test_class_grpowned_eh
    raise NotImplementedError, 'Need to write test_class_grpowned_eh'
  end

  def test_class_identical_eh
    raise NotImplementedError, 'Need to write test_class_identical_eh'
  end

  def test_class_join
    raise NotImplementedError, 'Need to write test_class_join'
  end

  def test_class_lchmod
    raise NotImplementedError, 'Need to write test_class_lchmod'
  end

  def test_class_lchown
    raise NotImplementedError, 'Need to write test_class_lchown'
  end

  def test_class_link
    raise NotImplementedError, 'Need to write test_class_link'
  end

  def test_class_lstat
    raise NotImplementedError, 'Need to write test_class_lstat'
  end

  def test_class_mtime
    raise NotImplementedError, 'Need to write test_class_mtime'
  end

  def test_class_owned_eh
    raise NotImplementedError, 'Need to write test_class_owned_eh'
  end

  def test_class_pipe_eh
    raise NotImplementedError, 'Need to write test_class_pipe_eh'
  end

  def test_class_readable_eh
    raise NotImplementedError, 'Need to write test_class_readable_eh'
  end

  def test_class_readable_real_eh
    raise NotImplementedError, 'Need to write test_class_readable_real_eh'
  end

  def test_class_readlink
    raise NotImplementedError, 'Need to write test_class_readlink'
  end

  def test_class_rename
    raise NotImplementedError, 'Need to write test_class_rename'
  end

  def test_class_setgid_eh
    raise NotImplementedError, 'Need to write test_class_setgid_eh'
  end

  def test_class_setuid_eh
    raise NotImplementedError, 'Need to write test_class_setuid_eh'
  end

  def test_class_size
    raise NotImplementedError, 'Need to write test_class_size'
  end

  def test_class_size_eh
    raise NotImplementedError, 'Need to write test_class_size_eh'
  end

  def test_class_socket_eh
    raise NotImplementedError, 'Need to write test_class_socket_eh'
  end

  def test_class_split
    raise NotImplementedError, 'Need to write test_class_split'
  end

  def test_class_stat
    raise NotImplementedError, 'Need to write test_class_stat'
  end

  def test_class_sticky_eh
    raise NotImplementedError, 'Need to write test_class_sticky_eh'
  end

  def test_class_symlink
    raise NotImplementedError, 'Need to write test_class_symlink'
  end

  def test_class_symlink_eh
    raise NotImplementedError, 'Need to write test_class_symlink_eh'
  end

  def test_class_truncate
    raise NotImplementedError, 'Need to write test_class_truncate'
  end

  def test_class_umask
    raise NotImplementedError, 'Need to write test_class_umask'
  end

  def test_class_unlink
    raise NotImplementedError, 'Need to write test_class_unlink'
  end

  def test_class_utime
    raise NotImplementedError, 'Need to write test_class_utime'
  end

  def test_class_writable_eh
    raise NotImplementedError, 'Need to write test_class_writable_eh'
  end

  def test_class_writable_real_eh
    raise NotImplementedError, 'Need to write test_class_writable_real_eh'
  end

  def test_class_zero_eh
    raise NotImplementedError, 'Need to write test_class_zero_eh'
  end

  def test_atime
    raise NotImplementedError, 'Need to write test_atime'
  end

  def test_chmod
    raise NotImplementedError, 'Need to write test_chmod'
  end

  def test_chown
    raise NotImplementedError, 'Need to write test_chown'
  end

  def test_ctime
    raise NotImplementedError, 'Need to write test_ctime'
  end

  def test_flock
    raise NotImplementedError, 'Need to write test_flock'
  end

  def test_lstat
    raise NotImplementedError, 'Need to write test_lstat'
  end

  def test_mtime
    raise NotImplementedError, 'Need to write test_mtime'
  end

  def test_path
    raise NotImplementedError, 'Need to write test_path'
  end

  def test_truncate
    raise NotImplementedError, 'Need to write test_truncate'
  end
end

class TestTagLib < Test::Unit::TestCase
  def test_class_taglib_audioproperties_bitrate
    raise NotImplementedError, 'Need to write test_class_taglib_audioproperties_bitrate'
  end

  def test_class_taglib_audioproperties_channels
    raise NotImplementedError, 'Need to write test_class_taglib_audioproperties_channels'
  end

  def test_class_taglib_audioproperties_length
    raise NotImplementedError, 'Need to write test_class_taglib_audioproperties_length'
  end

  def test_class_taglib_audioproperties_samplerate
    raise NotImplementedError, 'Need to write test_class_taglib_audioproperties_samplerate'
  end

  def test_class_taglib_file_audioproperties
    raise NotImplementedError, 'Need to write test_class_taglib_file_audioproperties'
  end

  def test_class_taglib_file_free
    raise NotImplementedError, 'Need to write test_class_taglib_file_free'
  end

  def test_class_taglib_file_new
    raise NotImplementedError, 'Need to write test_class_taglib_file_new'
  end

  def test_class_taglib_file_new_type
    raise NotImplementedError, 'Need to write test_class_taglib_file_new_type'
  end

  def test_class_taglib_file_save
    raise NotImplementedError, 'Need to write test_class_taglib_file_save'
  end

  def test_class_taglib_file_tag
    raise NotImplementedError, 'Need to write test_class_taglib_file_tag'
  end

  def test_class_taglib_tag_album
    raise NotImplementedError, 'Need to write test_class_taglib_tag_album'
  end

  def test_class_taglib_tag_artist
    raise NotImplementedError, 'Need to write test_class_taglib_tag_artist'
  end

  def test_class_taglib_tag_comment
    raise NotImplementedError, 'Need to write test_class_taglib_tag_comment'
  end

  def test_class_taglib_tag_genre
    raise NotImplementedError, 'Need to write test_class_taglib_tag_genre'
  end

  def test_class_taglib_tag_set_album
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_album'
  end

  def test_class_taglib_tag_set_artist
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_artist'
  end

  def test_class_taglib_tag_set_comment
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_comment'
  end

  def test_class_taglib_tag_set_genre
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_genre'
  end

  def test_class_taglib_tag_set_title
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_title'
  end

  def test_class_taglib_tag_set_track
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_track'
  end

  def test_class_taglib_tag_set_year
    raise NotImplementedError, 'Need to write test_class_taglib_tag_set_year'
  end

  def test_class_taglib_tag_title
    raise NotImplementedError, 'Need to write test_class_taglib_tag_title'
  end

  def test_class_taglib_tag_track
    raise NotImplementedError, 'Need to write test_class_taglib_tag_track'
  end

  def test_class_taglib_tag_year
    raise NotImplementedError, 'Need to write test_class_taglib_tag_year'
  end
end

# Number of errors detected: 90
